# NumPy Indexing (2D) and Selection

In [1]:
import numpy as np

In [2]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [3]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
arr_2d[0][0]

5

In [5]:
arr_2d[2][1]

40

In [6]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [7]:
arr = np.arange(1, 11)

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [10]:
bool_arr = arr > 5

In [11]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [12]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [13]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [14]:
arr_2d = np.arange(50).reshape(5, 10)

In [15]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [17]:
arr_2d[3, 1:6]

array([31, 32, 33, 34, 35])