# NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
mat = np.array(my_mat)

In [7]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.linspace(0, 5, 11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.30294549, 0.37255048, 0.72072048, 0.00495968, 0.33432538])

In [16]:
np.random.rand(5, 5)

array([[0.49576221, 0.91080435, 0.89707129, 0.09252259, 0.38999028],
       [0.8995918 , 0.92372436, 0.15947263, 0.57325731, 0.43994968],
       [0.69258531, 0.91256493, 0.65375284, 0.99021953, 0.03112966],
       [0.25113558, 0.57538301, 0.34859267, 0.57187513, 0.63947323],
       [0.09294844, 0.49719623, 0.83311102, 0.7594366 , 0.09626086]])

In [17]:
np.random.randn(2)

array([0.23572321, 1.16005712])

In [18]:
np.random.randn(2, 2)

array([[ 0.07290107, -0.17371671],
       [ 1.41925915,  0.59406996]])

In [19]:
np.random.randint(0, 100)

20

In [20]:
np.random.randint(0, 100, 10)

array([15, 92, 87,  1, 61, 80, 91,  6, 85, 91])

In [21]:
np.random.randint(0, 100, (10, 10))

array([[92, 86, 39, 20, 61,  5, 29, 54, 79, 96],
       [32,  5, 57, 21, 86,  3, 29, 56, 15, 73],
       [57, 72, 10,  0, 51, 96, 12, 78, 96,  7],
       [29, 52, 93, 59, 36,  1, 63,  8, 70, 79],
       [21, 31, 35, 96, 26, 39, 63, 92, 50, 58],
       [ 0, 17, 81, 56,  1, 49, 81, 28, 14, 95],
       [52, 63, 62, 26,  6, 26, 41, 22, 88, 31],
       [27, 16, 16, 45, 93, 20, 36, 45, 83, 54],
       [16, 62, 57, 17, 78, 35,  1, 63, 81, 79],
       [59,  7, 36, 89,  4, 33, 33, 60, 12,  0]])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr.max()

24

In [26]:
arr.min()

0

In [27]:
arr.argmax()

24

In [28]:
arr.argmin()

0

In [32]:
arr.shape

(25,)

In [31]:
arr.reshape(5, 5).shape

(5, 5)

In [33]:
arr.dtype

dtype('int64')